-- Generated by an offline Prisma schema diff; no existing records are rewritten.
ALTER TABLE `KnowledgeLibrary` ADD COLUMN `adminDisabledAt` DATETIME(3) NULL;

ALTER TABLE `CreditHourSubmission`
  MODIFY `status` ENUM('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'PENDING_MANUAL_REVIEW') NOT NULL DEFAULT 'PENDING_REVIEW';

ALTER TABLE `CreditHourDecisionEvent`
  MODIFY `fromStatus` ENUM('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'PENDING_MANUAL_REVIEW') NOT NULL,
  MODIFY `toStatus` ENUM('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'PENDING_MANUAL_REVIEW') NOT NULL;

ALTER TABLE `CreditHourCleanupOperation`
  ADD COLUMN `attempts` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `leaseOwnerToken` VARCHAR(191) NULL,
  ADD COLUMN `leasedUntil` DATETIME(3) NULL,
  ADD COLUMN `nextAttemptAt` DATETIME(3) NULL;

CREATE TABLE `CreditHourUploadOperation` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `idempotencyKey` VARCHAR(191) NOT NULL,
  `requestHash` CHAR(64) NOT NULL,
  `manifest` JSON NOT NULL,
  `status` ENUM('UPLOADING', 'COMMITTED', 'CLEANUP_PENDING', 'CLEANING', 'CLEANUP_FAILED', 'CLEANED') NOT NULL DEFAULT 'UPLOADING',
  `leaseOwnerToken` VARCHAR(191) NULL,
  `leasedUntil` DATETIME(3) NULL,
  `nextAttemptAt` DATETIME(3) NULL,
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `errorMessage` VARCHAR(500) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `CreditHourUploadOperation_userId_idempotencyKey_idx`(`userId`, `idempotencyKey`),
  INDEX `CreditHourUploadOperation_status_nextAttemptAt_leasedUntil_idx`(`status`, `nextAttemptAt`, `leasedUntil`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX `CreditHourCleanupOperation_status_nextAttemptAt_leasedUntil_idx`
  ON `CreditHourCleanupOperation`(`status`, `nextAttemptAt`, `leasedUntil`);

ALTER TABLE `CreditHourUploadOperation`
  ADD CONSTRAINT `CreditHourUploadOperation_userId_fkey`
  FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
