ALTER TABLE `QuizQuestion`
  MODIFY `type` ENUM('SINGLE', 'MULTIPLE', 'TRUE_FALSE', 'SHORT_ANSWER') NOT NULL,
  ADD COLUMN `gradingRubric` JSON NULL,
  ADD COLUMN `maxScore` INTEGER NOT NULL DEFAULT 1;
